@@ -10,31 +10,55 @@ jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        uses: actions/checkout@v4

      - name: Check if package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found, running npm install to generate it."
            npm install
          fi
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        continue-on-error: true  # Prevents failure if package-lock.json is missing

      - name: Build project
        run: npm run build

      - name: List dist directory (debugging step)
        run: ls -la dist

      - name: Archive production artifact
        uses: actions/upload-artifact@main
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 5  # Ensures artifact doesn't expire quickly

  deploy:
    name: Deploy ðŸš€
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@main
        uses: actions/checkout@v4

      - name: List artifacts before download (debugging step)
        run: ls -la

      - name: Download artifact
        uses: actions/download-artifact@main
        uses: actions/download-artifact@v4
        with: 
          name: dist
          path: dist

      - name: List dist directory after download (debugging step)
        run: ls -la dist

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: ftp.enterflash.com
          username: testcicd@enterflash.com
          password: ${{ secrets.ftp_password }}
          server: ftp.eportal.pitesindh.edu.pk
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
